# Generated by Django 4.2.3 on 2023-10-24 17:27

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[accounts.validators.email_validator]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[accounts.validators.username_regex_validator, accounts.validators.username_length_validator]),
        ),
    ]
