version: '3.3'

services:
  react-app:
    image: antonio0911/clonestagram-react:v1.0
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "start"]

  django-app:
    image: antonio0911/clonestagram-django:v1.0
    build: ./backend
    # command: gunicorn clonestagram.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file:
      - ./backend/.env
    depends_on:
      - react-app

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data

